DROP TABLE IF EXISTS books;

CREATE TABLE books(
id INT PRIMARY KEY,
price INT DEFAULT NULL,
price_old VARCHAR(250) DEFAULT NULL,
title VARCHAR(250) NOT NULL,
author_id INT NOT NULL
);

DROP TABLE IF EXISTS authors;

CREATE TABLE authors(
id INT PRIMARY KEY,
first_name VARCHAR(250) NOT NULL,
last_name VARCHAR(250) NOT NULL
);